import {
  BadRequestException,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import { DataSource } from 'typeorm';
import {
  CreateExpenseCategoryDto,
  CreateExpenseDto,
  ListExpensesDto,
  ReportRangeDto,
  UpdateExpenseCategoryDto,
  UpdateExpenseDto,
} from './dto/accounting.dto';

@Injectable()
export class AccountingService {
  constructor(private readonly ds: DataSource) {}

  // ─── Expense Categories ──────────────────────────────────────────────
  listCategories(includeInactive = false) {
    return this.ds.query(
      `SELECT * FROM expense_categories
       ${includeInactive ? '' : 'WHERE is_active = TRUE'}
       ORDER BY name_ar`,
    );
  }

  async createCategory(dto: CreateExpenseCategoryDto) {
    const [row] = await this.ds.query(
      `INSERT INTO expense_categories
         (code, name_ar, name_en, is_fixed, allocate_to_cogs)
       VALUES ($1,$2,$3,$4,$5)
       RETURNING *`,
      [
        dto.code,
        dto.name_ar,
        dto.name_en ?? null,
        dto.is_fixed ?? false,
        dto.allocate_to_cogs ?? false,
      ],
    );
    return row;
  }

  async updateCategory(id: string, dto: UpdateExpenseCategoryDto) {
    const fields: string[] = [];
    const params: any[] = [];
    let i = 1;
    for (const [k, v] of Object.entries(dto)) {
      if (v === undefined) continue;
      fields.push(`${k} = $${i++}`);
      params.push(v);
    }
    if (!fields.length) throw new BadRequestException('No fields to update');
    params.push(id);
    const [row] = await this.ds.query(
      `UPDATE expense_categories SET ${fields.join(', ')}
       WHERE id = $${i} RETURNING *`,
      params,
    );
    if (!row) throw new NotFoundException('التصنيف غير موجود');
    return row;
  }

  async deleteCategory(id: string) {
    const [{ n }] = await this.ds.query(
      `SELECT COUNT(*)::int AS n FROM expenses WHERE category_id = $1`,
      [id],
    );
    if (Number(n) > 0) {
      // Soft-delete (archive) when in use
      const [row] = await this.ds.query(
        `UPDATE expense_categories SET is_active = false
          WHERE id = $1 RETURNING id`,
        [id],
      );
      if (!row) throw new NotFoundException('التصنيف غير موجود');
      return { archived: true };
    }
    // Hard-delete when no expenses reference it
    const res = await this.ds.query(
      `DELETE FROM expense_categories WHERE id = $1 RETURNING id`,
      [id],
    );
    if (!res.length) throw new NotFoundException('التصنيف غير موجود');
    return { archived: true };
  }

  // ─── Expenses ────────────────────────────────────────────────────────
  async createExpense(dto: CreateExpenseDto, userId: string) {
    return this.ds.transaction(async (em) => {
      // `expense_no` is auto-generated by the `trg_set_expense_no` trigger
      // when NULL is passed. We omit it from the column list and pass NULL
      // so the trigger fires before the NOT-NULL check is evaluated.
      const [row] = await em.query(
        `INSERT INTO expenses
           (expense_no, warehouse_id, cashbox_id, category_id, amount,
            payment_method, expense_date, description, receipt_url, vendor_name,
            created_by)
         VALUES (NULL,$1,$2,$3,$4,$5::payment_method_code,COALESCE($6,CURRENT_DATE),$7,$8,$9,$10)
         RETURNING *`,
        [
          dto.warehouse_id,
          dto.cashbox_id ?? null,
          dto.category_id,
          dto.amount,
          dto.payment_method ?? 'cash',
          dto.expense_date ?? null,
          dto.description ?? null,
          dto.receipt_url ?? null,
          dto.vendor_name ?? null,
          userId,
        ],
      );
      return row;
    });
  }

  async updateExpense(id: string, dto: UpdateExpenseDto) {
    const fields: string[] = [];
    const params: any[] = [];
    let i = 1;
    for (const [k, v] of Object.entries(dto)) {
      if (v === undefined) continue;
      fields.push(`${k} = $${i++}`);
      params.push(v);
    }
    if (!fields.length) throw new BadRequestException('No fields to update');
    fields.push(`updated_at = NOW()`);
    params.push(id);
    const [row] = await this.ds.query(
      `UPDATE expenses SET ${fields.join(', ')}
       WHERE id = $${i} AND is_approved = FALSE
       RETURNING *`,
      params,
    );
    if (!row)
      throw new NotFoundException(
        'المصروف غير موجود أو تم اعتماده بالفعل',
      );
    return row;
  }

  async approveExpense(id: string, userId: string) {
    return this.ds.transaction(async (em) => {
      const [exp] = await em.query(
        `SELECT * FROM expenses WHERE id = $1 FOR UPDATE`,
        [id],
      );
      if (!exp) throw new NotFoundException('المصروف غير موجود');
      if (exp.is_approved)
        throw new BadRequestException('تم اعتماد هذا المصروف من قبل');

      const [row] = await em.query(
        `UPDATE expenses SET is_approved = TRUE, approved_by = $1, updated_at = NOW()
         WHERE id = $2 RETURNING *`,
        [userId, id],
      );

      // Post a cashbox transaction if the expense is paid in cash
      if (exp.payment_method === 'cash' && exp.cashbox_id) {
        const [{ current_balance }] = await em.query(
          `SELECT current_balance FROM cashboxes WHERE id = $1 FOR UPDATE`,
          [exp.cashbox_id],
        );
        const newBalance = Number(current_balance) - Number(exp.amount);
        await em.query(
          `INSERT INTO cashbox_transactions
             (cashbox_id, direction, amount, category, reference_type, reference_id,
              balance_after, notes, user_id)
           VALUES ($1,'out',$2,'expense','expense'::entity_type,$3,$4,$5,$6)`,
          [
            exp.cashbox_id,
            exp.amount,
            id,
            newBalance,
            exp.description ?? `Expense ${exp.expense_no}`,
            userId,
          ],
        );
        await em.query(
          `UPDATE cashboxes SET current_balance = $1, updated_at = NOW()
           WHERE id = $2`,
          [newBalance, exp.cashbox_id],
        );
      }

      return row;
    });
  }

  async deleteExpense(id: string) {
    const res = await this.ds.query(
      `DELETE FROM expenses WHERE id = $1 AND is_approved = FALSE RETURNING id`,
      [id],
    );
    if (!res.length)
      throw new NotFoundException(
        'المصروف غير موجود أو تم اعتماده ولا يمكن حذفه',
      );
    return { deleted: true };
  }

  async listExpenses(filters: ListExpensesDto) {
    const conds: string[] = [];
    const ps: any[] = [];
    if (filters.from) {
      ps.push(filters.from);
      conds.push(`e.expense_date >= $${ps.length}`);
    }
    if (filters.to) {
      ps.push(filters.to);
      conds.push(`e.expense_date <= $${ps.length}`);
    }
    if (filters.category_id) {
      ps.push(filters.category_id);
      conds.push(`e.category_id = $${ps.length}`);
    }
    if (filters.warehouse_id) {
      ps.push(filters.warehouse_id);
      conds.push(`e.warehouse_id = $${ps.length}`);
    }
    if (filters.status === 'approved') conds.push(`e.is_approved = TRUE`);
    else if (filters.status === 'pending') conds.push(`e.is_approved = FALSE`);
    if (filters.q) {
      ps.push(`%${filters.q}%`);
      conds.push(
        `(e.description ILIKE $${ps.length} OR e.vendor_name ILIKE $${ps.length} OR e.expense_no ILIKE $${ps.length})`,
      );
    }
    const where = conds.length ? `WHERE ${conds.join(' AND ')}` : '';
    ps.push(filters.limit ?? 100);
    ps.push(filters.offset ?? 0);

    const rows = await this.ds.query(
      `SELECT e.*,
              c.name_ar AS category_name,
              c.code    AS category_code,
              w.name_ar AS warehouse_name,
              uc.full_name AS created_by_name,
              ua.full_name AS approved_by_name
       FROM expenses e
       LEFT JOIN expense_categories c ON c.id = e.category_id
       LEFT JOIN warehouses w         ON w.id = e.warehouse_id
       LEFT JOIN users uc             ON uc.id = e.created_by
       LEFT JOIN users ua             ON ua.id = e.approved_by
       ${where}
       ORDER BY e.expense_date DESC, e.created_at DESC
       LIMIT $${ps.length - 1} OFFSET $${ps.length}`,
      ps,
    );

    const [tot] = await this.ds.query(
      `SELECT COUNT(*)::int AS total, COALESCE(SUM(amount),0)::numeric AS total_amount
       FROM expenses e ${where}`,
      ps.slice(0, ps.length - 2),
    );

    return { items: rows, total: tot.total, total_amount: Number(tot.total_amount) };
  }

  // ─── Reports ─────────────────────────────────────────────────────────

  /** Profit & Loss for a date range */
  /**
   * Smart human-readable analysis of a P&L range. Returns Arabic strings the
   * UI can show directly (e.g. "ربح جيد" / "خسارة — السبب: زيادة المصروفات").
   */
  async profitAndLossAnalysis(dto: ReportRangeDto) {
    const pl = await this.profitAndLoss(dto);
    const revenue = Number(pl.revenue || 0);
    const netRev = Number(pl.net_revenue || 0);
    const netProfit = Number(pl.net_profit || 0);
    const cogs = Number(pl.cogs || 0);
    const expenses = Number(pl.total_expenses || 0);
    const returns = Number(pl.returns || 0);
    const grossPct = Number(pl.gross_margin_pct || 0);
    const netPct = Number(pl.net_margin_pct || 0);

    // Headline classification
    let headline: 'profit' | 'loss' | 'breakeven' = 'breakeven';
    let headlineLabel = 'تعادل';
    let headlineTone: 'green' | 'red' | 'amber' = 'amber';
    if (netProfit > 0) {
      headline = 'profit';
      headlineTone = 'green';
      if (netPct >= 20) headlineLabel = 'ربح ممتاز';
      else if (netPct >= 10) headlineLabel = 'ربح جيد';
      else headlineLabel = 'ربح ضعيف';
    } else if (netProfit < 0) {
      headline = 'loss';
      headlineTone = 'red';
      headlineLabel = 'خسارة';
    }

    // Reasons (plain-Arabic diagnostics, ordered by severity)
    const reasons: Array<{ code: string; message: string; severity: 'info' | 'warning' | 'critical' }> = [];

    if (revenue === 0) {
      reasons.push({
        code: 'no_sales',
        message: 'لا توجد مبيعات في هذه الفترة.',
        severity: 'critical',
      });
    }
    if (returns > 0 && revenue > 0) {
      const retPct = (returns / revenue) * 100;
      if (retPct >= 20) {
        reasons.push({
          code: 'high_returns',
          message: `نسبة المرتجعات مرتفعة (${retPct.toFixed(1)}% من الإيراد) — راجع أسباب الإرجاع.`,
          severity: 'critical',
        });
      } else if (retPct >= 10) {
        reasons.push({
          code: 'elevated_returns',
          message: `نسبة المرتجعات ${retPct.toFixed(1)}% — تستحق المتابعة.`,
          severity: 'warning',
        });
      }
    }
    if (cogs > 0 && revenue > 0) {
      const cogsPct = (cogs / revenue) * 100;
      if (cogsPct >= 80) {
        reasons.push({
          code: 'high_cogs',
          message: `تكلفة البضاعة المباعة ${cogsPct.toFixed(0)}% من الإيراد — الأسعار منخفضة أو التكلفة مرتفعة.`,
          severity: 'warning',
        });
      }
    }
    if (expenses > 0 && netRev > 0) {
      const expPct = (expenses / netRev) * 100;
      if (expPct >= 40) {
        reasons.push({
          code: 'high_expenses',
          message: `المصروفات التشغيلية ${expPct.toFixed(0)}% من صافي الإيراد — راجع أكبر بنود المصاريف.`,
          severity: 'warning',
        });
      }
    }
    if (grossPct < 15 && revenue > 0) {
      reasons.push({
        code: 'low_margin',
        message: `هامش الربح الإجمالي منخفض (${grossPct.toFixed(1)}%) — فكّر في رفع الأسعار أو خفض التكلفة.`,
        severity: 'warning',
      });
    }
    if (headline === 'profit' && reasons.length === 0) {
      reasons.push({
        code: 'healthy',
        message: 'المؤشرات كلها في المدى الصحي. استمر!',
        severity: 'info',
      });
    }

    // Actionable suggestions
    const suggestions: string[] = [];
    if (returns > 0) {
      suggestions.push('راجع تقرير المرتجعات لمعرفة السبب الأكثر تكراراً.');
    }
    if (expenses > revenue * 0.3) {
      suggestions.push('قارن المصاريف بالفترة السابقة لكشف البنود التي زادت.');
    }
    if (netPct < 5 && netPct > 0) {
      suggestions.push('أضف منتجات ذات هامش أعلى، أو اعرض عروض تسريع الدوران.');
    }
    if (headline === 'loss') {
      suggestions.push('حدّد أكبر 3 بنود مصاريف وتفاوض أو ألغِ ما يمكن تأجيله.');
      suggestions.push('افحص أسعار البيع — هل تغطي التكلفة + هامش أدنى 20%؟');
    }

    return {
      ...pl,
      analysis: {
        headline,
        headline_label: headlineLabel,
        headline_tone: headlineTone,
        reasons,
        suggestions,
      },
    };
  }

  async profitAndLoss(dto: ReportRangeDto) {
    const wCond = dto.warehouse_id ? `AND warehouse_id = $3` : '';
    const params: any[] = [dto.from, dto.to];
    if (dto.warehouse_id) params.push(dto.warehouse_id);

    // Revenue (completed invoices)
    const [revRow] = await this.ds.query(
      `SELECT
         COALESCE(SUM(grand_total),0)::numeric    AS revenue,
         COALESCE(SUM(discount_total),0)::numeric AS discounts,
         COUNT(*)::int                            AS invoice_count
       FROM invoices
       WHERE status IN ('completed','paid','partially_paid')
         AND created_at::date BETWEEN $1 AND $2
         ${wCond}`,
      params,
    );

    // COGS — sum(invoice_lines.qty * variant.cost_price)
    const [cogsRow] = await this.ds.query(
      `SELECT COALESCE(SUM(il.qty * COALESCE(pv.cost_price,0)),0)::numeric AS cogs
       FROM invoice_lines il
       JOIN invoices i        ON i.id = il.invoice_id
       LEFT JOIN product_variants pv ON pv.id = il.variant_id
       WHERE i.status IN ('completed','paid','partially_paid')
         AND i.created_at::date BETWEEN $1 AND $2
         ${dto.warehouse_id ? 'AND i.warehouse_id = $3' : ''}`,
      params,
    );

    // Returns (refunds reduce revenue)
    const [retRow] = await this.ds.query(
      `SELECT COALESCE(SUM(total_refund),0)::numeric AS returns_total
       FROM return_receipts
       WHERE status IN ('completed','paid','partially_paid')
         AND created_at::date BETWEEN $1 AND $2
         ${dto.warehouse_id ? 'AND warehouse_id = $3' : ''}`,
      params,
    );

    // Expenses by category
    const expByCat = await this.ds.query(
      `SELECT c.code, c.name_ar, c.is_fixed, c.allocate_to_cogs,
              COALESCE(SUM(e.amount),0)::numeric AS total
       FROM expenses e
       JOIN expense_categories c ON c.id = e.category_id
       WHERE e.is_approved = TRUE
         AND e.expense_date BETWEEN $1 AND $2
         ${dto.warehouse_id ? 'AND e.warehouse_id = $3' : ''}
       GROUP BY c.id
       ORDER BY total DESC`,
      params,
    );

    const revenue = Number(revRow.revenue);
    const cogs = Number(cogsRow.cogs);
    const returns = Number(retRow.returns_total);
    const totalExpenses = expByCat.reduce(
      (s: number, r: any) => s + Number(r.total),
      0,
    );
    const allocatedExpenses = expByCat
      .filter((r: any) => r.allocate_to_cogs)
      .reduce((s: number, r: any) => s + Number(r.total), 0);
    const operatingExpenses = totalExpenses - allocatedExpenses;

    const netRevenue = revenue - returns;
    const grossProfit = netRevenue - cogs - allocatedExpenses;
    const netProfit = grossProfit - operatingExpenses;

    return {
      range: { from: dto.from, to: dto.to },
      warehouse_id: dto.warehouse_id ?? null,
      revenue,
      discounts: Number(revRow.discounts),
      invoice_count: revRow.invoice_count,
      returns,
      net_revenue: netRevenue,
      cogs,
      allocated_expenses: allocatedExpenses,
      gross_profit: grossProfit,
      operating_expenses: operatingExpenses,
      total_expenses: totalExpenses,
      net_profit: netProfit,
      gross_margin_pct: netRevenue > 0 ? (grossProfit / netRevenue) * 100 : 0,
      net_margin_pct: netRevenue > 0 ? (netProfit / netRevenue) * 100 : 0,
      expenses_by_category: expByCat,
    };
  }

  /** Cashflow summary using cashbox_transactions */
  async cashflow(dto: ReportRangeDto) {
    const params: any[] = [dto.from, dto.to];
    const wCond = dto.warehouse_id
      ? `AND cb.warehouse_id = $3`
      : '';
    if (dto.warehouse_id) params.push(dto.warehouse_id);

    const byCat = await this.ds.query(
      `SELECT t.category, t.direction,
              COALESCE(SUM(t.amount),0)::numeric AS total,
              COUNT(*)::int                     AS count
       FROM cashbox_transactions t
       JOIN cashboxes cb ON cb.id = t.cashbox_id
       WHERE t.created_at::date BETWEEN $1 AND $2
         ${wCond}
       GROUP BY t.category, t.direction
       ORDER BY total DESC`,
      params,
    );

    const inflow = byCat
      .filter((r: any) => r.direction === 'in')
      .reduce((s: number, r: any) => s + Number(r.total), 0);
    const outflow = byCat
      .filter((r: any) => r.direction === 'out')
      .reduce((s: number, r: any) => s + Number(r.total), 0);

    return {
      range: { from: dto.from, to: dto.to },
      inflow,
      outflow,
      net: inflow - outflow,
      breakdown: byCat,
    };
  }

  /** Trial balance — opening balance + period activity per cashbox */
  async trialBalance(dto: ReportRangeDto) {
    const params: any[] = [dto.from, dto.to];
    const wCond = dto.warehouse_id ? `AND cb.warehouse_id = $3` : '';
    if (dto.warehouse_id) params.push(dto.warehouse_id);

    return this.ds.query(
      `SELECT
         cb.id                                   AS cashbox_id,
         cb.name_ar                              AS cashbox_name,
         cb.warehouse_id,
         w.name_ar                               AS warehouse_name,
         cb.current_balance::numeric             AS current_balance,
         COALESCE(SUM(CASE WHEN t.direction = 'in'  AND t.created_at::date BETWEEN $1 AND $2
                          THEN t.amount END),0)::numeric AS period_in,
         COALESCE(SUM(CASE WHEN t.direction = 'out' AND t.created_at::date BETWEEN $1 AND $2
                          THEN t.amount END),0)::numeric AS period_out,
         COALESCE(SUM(CASE WHEN t.direction = 'in'  AND t.created_at::date < $1
                          THEN t.amount END),0)::numeric AS opening_in,
         COALESCE(SUM(CASE WHEN t.direction = 'out' AND t.created_at::date < $1
                          THEN t.amount END),0)::numeric AS opening_out
       FROM cashboxes cb
       LEFT JOIN warehouses w ON w.id = cb.warehouse_id
       LEFT JOIN cashbox_transactions t ON t.cashbox_id = cb.id
       WHERE cb.is_active = TRUE
         ${wCond}
       GROUP BY cb.id, w.name_ar
       ORDER BY cb.name_ar`,
      params,
    );
  }

  /** General ledger — paginated cashbox transactions */
  async generalLedger(filters: {
    from?: string;
    to?: string;
    cashbox_id?: string;
    category?: string;
    limit?: number;
    offset?: number;
  }) {
    const conds: string[] = [];
    const ps: any[] = [];
    if (filters.from) {
      ps.push(filters.from);
      conds.push(`t.created_at::date >= $${ps.length}`);
    }
    if (filters.to) {
      ps.push(filters.to);
      conds.push(`t.created_at::date <= $${ps.length}`);
    }
    if (filters.cashbox_id) {
      ps.push(filters.cashbox_id);
      conds.push(`t.cashbox_id = $${ps.length}`);
    }
    if (filters.category) {
      ps.push(filters.category);
      conds.push(`t.category = $${ps.length}`);
    }
    const where = conds.length ? `WHERE ${conds.join(' AND ')}` : '';
    ps.push(filters.limit ?? 200);
    ps.push(filters.offset ?? 0);

    return this.ds.query(
      `SELECT t.*, cb.name_ar AS cashbox_name, u.full_name AS user_name
       FROM cashbox_transactions t
       LEFT JOIN cashboxes cb ON cb.id = t.cashbox_id
       LEFT JOIN users u      ON u.id  = t.user_id
       ${where}
       ORDER BY t.created_at DESC
       LIMIT $${ps.length - 1} OFFSET $${ps.length}`,
      ps,
    );
  }

  /** Quick financial KPIs for the accounting page header */
  async kpis() {
    const today = new Date().toISOString().slice(0, 10);
    const monthStart = today.slice(0, 7) + '-01';
    const [today_pl, month_pl] = await Promise.all([
      this.profitAndLoss({ from: today, to: today } as any),
      this.profitAndLoss({ from: monthStart, to: today } as any),
    ]);

    const [pendingRow] = await this.ds.query(
      `SELECT COUNT(*)::int AS pending_expenses,
              COALESCE(SUM(amount),0)::numeric AS pending_amount
       FROM expenses
       WHERE is_approved = FALSE`,
    );

    return {
      today: today_pl,
      month: month_pl,
      pending_expenses: pendingRow.pending_expenses,
      pending_amount: Number(pendingRow.pending_amount),
    };
  }
}
