import {
  BadRequestException,
  Injectable,
  NotFoundException,
  Optional,
} from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { DataSource, Repository } from 'typeorm';
import { InvoiceEntity } from './entities/invoice.entity';
import { CreateInvoiceDto } from './dto/invoice.dto';
import { RealtimeGateway } from '../realtime/realtime.gateway';
import { LoyaltyService } from '../loyalty/loyalty.service';
import { NotificationsService } from '../notifications/notifications.service';

@Injectable()
export class PosService {
  constructor(
    @InjectRepository(InvoiceEntity)
    private readonly invoices: Repository<InvoiceEntity>,
    private readonly ds: DataSource,
    @Optional() private readonly realtime?: RealtimeGateway,
    @Optional() private readonly loyalty?: LoyaltyService,
    @Optional() private readonly notifications?: NotificationsService,
  ) {}

  /**
   * Creates a full invoice atomically. invoice_no is auto-generated by the
   * BEFORE INSERT trigger (trg_set_invoice_no → next_doc_no('INV',...)).
   */
  async createInvoice(dto: CreateInvoiceDto, userId: string) {
    if (!dto.lines?.length) {
      throw new BadRequestException('Invoice must have at least one line');
    }

    // Salesperson is required on every invoice so performance reports and
    // commissions can attribute the sale. Front-end enforces this too; the
    // backend check is the source of truth.
    if (!dto.salesperson_id) {
      throw new BadRequestException('يجب اختيار البائع قبل حفظ الفاتورة');
    }

    // Require an open shift for the cashier before accepting a sale. Falls
    // back to any open shift this user holds (warehouse mismatch shouldn't
    // block the sale, but *no open shift* means the cashier is off-duty).
    const [openShift] = await this.ds.query(
      `SELECT id FROM shifts
         WHERE opened_by = $1 AND status = 'open'
         ORDER BY opened_at DESC LIMIT 1`,
      [userId],
    );
    if (!openShift) {
      throw new BadRequestException(
        'لا يمكن تسجيل فاتورة قبل فتح وردية جديدة — برجاء فتح الوردية أولاً',
      );
    }

    const subtotal = dto.lines.reduce(
      (s, l) => s + l.unit_price * l.qty - (l.discount || 0),
      0,
    );

    // VAT config (from settings) ───────────────────────────────────
    // Egypt standard: 14%, prices inclusive of VAT.
    const [vatRow] = await this.ds.query(
      `SELECT value FROM settings WHERE key = 'vat.config'`,
    );
    const vatConfig = vatRow?.value || {
      enabled: false,
      rate: 0,
      inclusive: true,
    };
    const vatEnabled = !!vatConfig.enabled;
    const vatRate: number = vatEnabled ? Number(vatConfig.rate || 0) : 0;
    const vatInclusive: boolean = vatConfig.inclusive !== false;

    // Loyalty redemption (optional)
    let loyalty_discount = 0;
    let applied_points = 0;
    if (dto.customer_id && dto.redeem_points && dto.redeem_points > 0) {
      if (!this.loyalty) {
        throw new BadRequestException('Loyalty service not available');
      }
      const preview = await this.loyalty.preview(
        dto.customer_id,
        dto.redeem_points,
        subtotal,
      );
      loyalty_discount = preview.applied_egp;
      applied_points = preview.applied_points;
    }

    const invoice_discount = (dto.discount_total || 0) + loyalty_discount;
    const net_before_tax = Math.max(0, subtotal - invoice_discount);

    // VAT computation:
    //  inclusive  → price already contains VAT → tax = gross * rate / (100 + rate)
    //  exclusive  → add tax on top → tax = net * rate / 100
    let tax_amount = 0;
    let grand_total = net_before_tax;
    if (vatEnabled && vatRate > 0) {
      if (vatInclusive) {
        tax_amount = (net_before_tax * vatRate) / (100 + vatRate);
        grand_total = net_before_tax;
      } else {
        tax_amount = (net_before_tax * vatRate) / 100;
        grand_total = net_before_tax + tax_amount;
      }
      tax_amount = Math.round(tax_amount * 100) / 100;
      grand_total = Math.round(grand_total * 100) / 100;
    }

    const paid_total = dto.payments.reduce((s, p) => s + p.amount, 0);

    if (paid_total < grand_total) {
      throw new BadRequestException(
        `Payment short: paid ${paid_total} < total ${grand_total}`,
      );
    }
    const change_amount = Math.max(0, paid_total - grand_total);

    // Pre-load variant + product info so we can snapshot name / sku / color / size
    const variantIds = Array.from(
      new Set(dto.lines.map((l) => l.variant_id)),
    );
    const variants = await this.ds.query(
      `
      SELECT v.id, v.sku, v.cost_price,
             c.name_ar    AS color_name,
             s.size_label AS size_label,
             p.name_ar    AS product_name
      FROM product_variants v
      JOIN products  p ON p.id = v.product_id
      LEFT JOIN colors c ON c.id = v.color_id
      LEFT JOIN sizes  s ON s.id = v.size_id
      WHERE v.id = ANY($1::uuid[])
      `,
      [variantIds],
    );
    const variantMap = new Map<string, any>(variants.map((v: any) => [v.id, v]));

    return this.ds.transaction(async (em) => {
      // Resolve current open shift + cashbox for cashbox auto-updates.
      // Prefer a shift opened for THIS warehouse, but fall back to any open
      // shift the cashier has — a mismatch between the POS warehouse and the
      // shift warehouse shouldn't silently orphan the invoice.
      const primaryShift = await em.query(
        `SELECT id, cashbox_id FROM shifts
           WHERE opened_by = $1 AND status = 'open'
             AND warehouse_id = $2
           ORDER BY opened_at DESC LIMIT 1`,
        [userId, dto.warehouse_id],
      );
      const fallbackShift = primaryShift.length
        ? primaryShift
        : await em.query(
            `SELECT id, cashbox_id FROM shifts
               WHERE opened_by = $1 AND status = 'open'
               ORDER BY opened_at DESC LIMIT 1`,
            [userId],
          );
      const shift = fallbackShift[0];
      let cashboxId: string | null = shift?.cashbox_id ?? null;
      if (!cashboxId) {
        const [cb] = await em.query(
          `SELECT id FROM cashboxes
             WHERE warehouse_id = $1 AND is_active = true
             ORDER BY created_at LIMIT 1`,
          [dto.warehouse_id],
        );
        cashboxId = cb?.id ?? null;
      }

      const [invoice] = await em.query(
        `
        INSERT INTO invoices
          (warehouse_id, customer_id, cashier_id, salesperson_id, status,
           subtotal, invoice_discount, tax_rate, tax_amount,
           grand_total, paid_amount, change_amount, notes,
           shift_id, completed_at)
        VALUES ($1,$2,$3,$4,'paid',$5,$6,$7,$8,$9,$10,$11,$12,$13, now())
        RETURNING *
        `,
        [
          dto.warehouse_id,
          dto.customer_id ?? null,
          userId,
          dto.salesperson_id ?? null,
          subtotal,
          invoice_discount,
          vatRate,
          tax_amount,
          grand_total,
          paid_total,
          change_amount,
          dto.notes ?? null,
          shift?.id ?? null,
        ],
      );

      for (const line of dto.lines) {
        const v = variantMap.get(line.variant_id);
        if (!v) {
          throw new BadRequestException(
            `Variant ${line.variant_id} not found`,
          );
        }
        const line_subtotal = line.qty * line.unit_price;
        const line_total = line_subtotal - (line.discount || 0);

        await em.query(
          `
          INSERT INTO invoice_items
            (invoice_id, variant_id,
             product_name_snapshot, sku_snapshot,
             color_name_snapshot, size_label_snapshot,
             quantity, unit_cost, unit_price,
             discount_amount, line_subtotal, line_total,
             salesperson_id)
          VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)
          `,
          [
            invoice.id,
            line.variant_id,
            v.product_name,
            v.sku,
            v.color_name ?? null,
            v.size_label ?? null,
            line.qty,
            Number(v.cost_price || 0),
            line.unit_price,
            line.discount ?? 0,
            line_subtotal,
            line_total,
            line.salesperson_id ?? dto.salesperson_id ?? null,
          ],
        );
      }

      // Decrement stock for each sold line (trigger updates `stock.quantity_on_hand`).
      for (const line of dto.lines) {
        const v = variantMap.get(line.variant_id);
        await em.query(
          `INSERT INTO stock_movements
             (variant_id, warehouse_id, movement_type, direction,
              quantity, unit_cost, reference_type, reference_id, user_id)
           VALUES ($1,$2,'sale','out',$3,$4,'invoice',$5,$6)`,
          [
            line.variant_id,
            dto.warehouse_id,
            line.qty,
            Number(v?.cost_price || 0),
            invoice.id,
            userId,
          ],
        );
      }

      for (const pay of dto.payments) {
        await em.query(
          `
          INSERT INTO invoice_payments
            (invoice_id, payment_method, amount, reference_number, received_by)
          VALUES ($1,$2,$3,$4,$5)
          `,
          [
            invoice.id,
            pay.payment_method,
            pay.amount,
            pay.reference ?? null,
            userId,
          ],
        );

        // Auto-update cashbox for cash payments.
        if (pay.payment_method === 'cash' && cashboxId) {
          await em.query(
            `SELECT fn_record_cashbox_txn($1,'in',$2,'sale','invoice',$3,$4,$5)`,
            [
              cashboxId,
              pay.amount,
              invoice.id,
              userId,
              `بيع — فاتورة ${invoice.invoice_no}`,
            ],
          );
        }
      }

      // Deduct loyalty points (if any) inside the same transaction
      if (applied_points > 0 && dto.customer_id && this.loyalty) {
        await this.loyalty.redeem(em, {
          customer_id: dto.customer_id,
          points: applied_points,
          invoice_id: invoice.id,
          user_id: userId,
        });
      }

      const result = {
        invoice_id: invoice.id,
        invoice_no: invoice.invoice_no,
        doc_no: invoice.invoice_no, // legacy alias
        grand_total,
        change_given: change_amount,
        tax_rate: vatRate,
        tax_amount,
        loyalty_discount,
        applied_points,
      };

      this.realtime?.emitPosEvent({
        type: 'invoice.created',
        payload: { ...result, cashier_id: userId, customer_id: dto.customer_id },
      });

      if (dto.customer_id && this.notifications) {
        this.sendThankYouNotification(invoice.id, userId).catch(() => {});
      }

      return result;
    });
  }

  /**
   * Enqueue the 'invoice.thank_you' WhatsApp template for the customer.
   */
  private async sendThankYouNotification(invoiceId: string, userId: string) {
    try {
      const config = await this.notifications!.getConfig();
      if (config?.auto_send_invoice_receipt === false) return;

      const [row] = await this.ds.query(
        `
        SELECT
          i.invoice_no AS doc_no, i.grand_total,
          c.full_name AS customer_name,
          c.phone     AS customer_phone,
          c.loyalty_points,
          (SELECT value->>'name' FROM settings WHERE key = 'shop.info') AS shop_name,
          COALESCE(
            (SELECT SUM(points)
             FROM customer_loyalty_transactions
             WHERE reference_type = 'invoice'
               AND reference_id = i.id
               AND direction = 'in'), 0
          )::int AS earned_points
        FROM invoices i
        LEFT JOIN customers c ON c.id = i.customer_id
        WHERE i.id = $1
        `,
        [invoiceId],
      );
      if (!row?.customer_phone) return;

      await this.notifications!.enqueueFromTemplate({
        code: 'invoice.thank_you',
        recipient: row.customer_phone,
        variables: {
          customer_name: row.customer_name,
          shop_name: row.shop_name || 'زهران',
          doc_no: row.doc_no,
          grand_total: Number(row.grand_total).toFixed(2),
          earned_points: row.earned_points ?? 0,
          loyalty_points: row.loyalty_points ?? 0,
        },
        reference_type: 'invoice',
        reference_id: invoiceId,
        created_by: userId,
      });
    } catch {
      /* silent */
    }
  }

  async findOne(id: string) {
    const inv = await this.invoices.findOne({ where: { id } });
    if (!inv) throw new NotFoundException(`Invoice ${id} not found`);
    const lines = await this.ds.query(
      `SELECT * FROM invoice_items WHERE invoice_id = $1 ORDER BY id`,
      [id],
    );
    const payments = await this.ds.query(
      `SELECT * FROM invoice_payments WHERE invoice_id = $1 ORDER BY paid_at`,
      [id],
    );
    return { ...inv, lines, payments };
  }

  /**
   * Rich payload for receipt printing — includes shop info, product names,
   * customer details, cashier name, salesperson name, and warehouse name.
   */
  async getReceipt(id: string) {
    const [inv] = await this.ds.query(
      `
      SELECT
        i.*,
        c.full_name   AS customer_name,
        c.phone       AS customer_phone,
        c.loyalty_points AS customer_loyalty_points,
        u.full_name   AS cashier_name,
        u.username    AS cashier_username,
        sp.full_name  AS salesperson_name,
        sp.username   AS salesperson_username,
        w.name        AS warehouse_name
      FROM invoices i
      LEFT JOIN customers c ON c.id = i.customer_id
      LEFT JOIN users     u ON u.id = i.cashier_id
      LEFT JOIN users     sp ON sp.id = i.salesperson_id
      LEFT JOIN warehouses w ON w.id = i.warehouse_id
      WHERE i.id = $1
      `,
      [id],
    );
    if (!inv) throw new NotFoundException(`Invoice ${id} not found`);

    const lines = await this.ds.query(
      `
      SELECT
        il.*,
        pv.barcode    AS barcode,
        p.name_en     AS product_name_en,
        sp.full_name  AS salesperson_name
      FROM invoice_items il
      LEFT JOIN product_variants pv ON pv.id = il.variant_id
      LEFT JOIN products         p  ON p.id  = pv.product_id
      LEFT JOIN users            sp ON sp.id = il.salesperson_id
      WHERE il.invoice_id = $1
      ORDER BY il.id
      `,
      [id],
    );

    const payments = await this.ds.query(
      `SELECT * FROM invoice_payments WHERE invoice_id = $1 ORDER BY paid_at`,
      [id],
    );

    const [shopRow, receiptRow, templatesRow, activeRow] = await Promise.all([
      this.ds
        .query(`SELECT value FROM settings WHERE key = 'shop.info'`)
        .then((r) => r[0]),
      this.ds
        .query(`SELECT value FROM settings WHERE key = 'shop.receipt'`)
        .then((r) => r[0]),
      this.ds
        .query(`SELECT value FROM settings WHERE key = 'shop.receipt_templates'`)
        .then((r) => r[0]),
      this.ds
        .query(`SELECT value FROM settings WHERE key = 'shop.receipt_active_template'`)
        .then((r) => r[0]),
    ]);
    const templates: any[] = Array.isArray(templatesRow?.value)
      ? templatesRow!.value
      : [];
    const activeId: string | undefined =
      typeof activeRow?.value === 'string'
        ? activeRow.value
        : activeRow?.value?.id;
    const active_template =
      templates.find((t) => t.id === activeId) || templates[0] || null;
    const shop = {
      ...(shopRow?.value ?? {}),
      ...(receiptRow?.value ?? {}),
      active_template,
    };

    const loyaltyTx = await this.ds.query(
      `
      SELECT direction, points, reason
      FROM customer_loyalty_transactions
      WHERE reference_type = 'invoice' AND reference_id = $1
      `,
      [id],
    );

    return { invoice: inv, lines, payments, shop, loyalty: loyaltyTx };
  }

  async listRecent(
    limit = 50,
    filters: {
      from?: string;
      to?: string;
      status?: string;
      q?: string;
      cashier_id?: string;
    } = {},
  ) {
    const conds: string[] = [];
    const params: any[] = [];
    if (filters.from) {
      params.push(filters.from);
      conds.push(`i.created_at::date >= $${params.length}::date`);
    }
    if (filters.to) {
      params.push(filters.to);
      conds.push(`i.created_at::date <= $${params.length}::date`);
    }
    if (filters.status && filters.status !== 'all') {
      params.push(filters.status);
      conds.push(`i.status = $${params.length}`);
    }
    if (filters.cashier_id) {
      params.push(filters.cashier_id);
      conds.push(`i.cashier_id = $${params.length}`);
    }
    if (filters.q) {
      params.push(`%${filters.q}%`);
      const p = params.length;
      conds.push(
        `(i.invoice_no ILIKE $${p} OR c.full_name ILIKE $${p} OR c.phone ILIKE $${p})`,
      );
    }
    const where = conds.length ? `WHERE ${conds.join(' AND ')}` : '';
    params.push(limit);
    return this.ds.query(
      `
      SELECT i.*,
             c.full_name AS customer_name,
             c.phone     AS customer_phone,
             u.full_name AS cashier_name,
             sp.full_name AS salesperson_name
      FROM invoices i
      LEFT JOIN customers c ON c.id = i.customer_id
      LEFT JOIN users     u ON u.id = i.cashier_id
      LEFT JOIN users    sp ON sp.id = i.salesperson_id
      ${where}
      ORDER BY i.created_at DESC
      LIMIT $${params.length}
      `,
      params,
    );
  }

  async voidInvoice(id: string, userId: string, reason: string) {
    await this.ds.query(`SELECT fn_void_invoice($1, $2, $3)`, [
      id,
      userId,
      reason,
    ]);
    this.realtime?.emitPosEvent({
      type: 'invoice.voided',
      payload: { invoice_id: id, reason, voided_by: userId },
    });
    return { voided: true };
  }

  /**
   * Edit a previously-issued invoice. Because invoices are immutable once
   * posted (stock moved, cash received, loyalty accrued), the "edit" here is
   * void-and-recreate: we reverse the original via fn_void_invoice and then
   * create a new invoice with the modified lines/payments. The new invoice
   * gets a `replaces_invoice_id` note in the `notes` field so auditors can
   * trace the relationship.
   */
  async editInvoice(
    id: string,
    dto: any,
    userId: string,
    reason: string,
  ) {
    // Void first (outside our create transaction — fn_void_invoice runs in its
    // own autonomous commit via plpgsql). If this throws, no new invoice is
    // created and the original stays intact.
    await this.ds.query(`SELECT fn_void_invoice($1, $2, $3)`, [
      id,
      userId,
      reason,
    ]);
    const tagged = {
      ...dto,
      notes: [dto.notes, `تعديل للفاتورة رقم ${id}`]
        .filter(Boolean)
        .join(' — '),
    };
    const created = await this.createInvoice(tagged, userId);
    this.realtime?.emitPosEvent({
      type: 'invoice.created',
      payload: {
        original_invoice_id: id,
        new_invoice_id: (created as any)?.id,
        edited_by: userId,
        edited: true,
      },
    });
    return { replaced: id, invoice: created };
  }
}
