-- Migration 110 — SUPERSEDED (PR-AUDIT-MIGRATION-110-RETIRE)
-- ═══════════════════════════════════════════════════════════════════════════
--
-- Status: NO-OP. The original PR-DRIFT-3G settlement-7 reconciliation work
-- this file was meant to perform was already applied to production through
-- other channels (verified 14 of 15 invariants — see "State proof" below).
-- This file is now a no-op so the migration runner records it as applied
-- and stops emitting `✗ 110_*.sql — syntax error at or near "||"` on every
-- container restart.
--
-- Original SQL preserved at git commit e7d340e:
--   git show e7d340e:database/migrations/110_pr_drift_3g_settlement7_reconciliation.sql
--
-- ─── Why the original failed ───────────────────────────────────────────────
--
-- Lines 478-481 of the original used `||` to concatenate the format string
-- of a `RAISE NOTICE` call:
--
--   RAISE NOTICE 'PR-DRIFT-3G post OK: balance=% trial=0 ... '
--             || 'settlement7_paired_drift=0 other_CT_only_settlement7_rows=0 '
--             || 'abu_youssef_213_credit=%',
--     v_cb_balance, v_payable_credit;
--
-- PostgreSQL's RAISE statement requires the format to be a SINGLE string
-- literal — `||` is not allowed in the format position. The parser fails
-- with `syntax error at or near "||"` and rolls back the migration tx,
-- so `schema_migrations` never records 110, so the runner re-attempts it
-- on every restart.
--
-- ─── Why we are NOT just fixing the syntax ─────────────────────────────────
--
-- Even with the `||` fixed, post-condition (h) at lines 464-476 hard-codes
-- `IF v_payable_credit <> 1345.00 THEN RAISE EXCEPTION ...`. That value was
-- the correct Abu Youssef 213 net credit on the original snapshot date
-- (2026-04-26), but Abu Youssef has had legitimate additional 213 activity
-- since then (further wage accruals + the JE-196 void from PR-262 cleanup).
-- The current value is 2,371.00. Fixing the syntax alone leaves the
-- migration brittle to a state-drift assertion failure on the next run,
-- and relaxing post-condition (h) weakens the original data-integrity
-- contract for no benefit (the work is already done).
--
-- ─── State proof (read-only audit, captured 2026-05-04) ────────────────────
--
-- Original migration's intended end-state vs current prod state:
--
--   ✓ CT 105 is_void = TRUE  (void_reason starts with the migration's
--                             exact string "PR-DRIFT-3G — direction-fix
--                             noise from settlement-7 chain…")
--   ✓ CT 107 is_void = TRUE
--   ✓ CT 108 is_void = FALSE, reference_type = 'employee_settlement',
--                              reference_id = 887ea7c4-…cb46cb33,
--                              amount = 100
--   ✓ JE-2026-000248 exists, is_posted=TRUE, is_void=FALSE,
--     reference_type = 'employee_settlement', reference_id = 887ea7c4-…,
--     line 1: DR 213 100, employee_user_id = 3800f38b-… (Abu Youssef)
--     line 2: CR 1111 100, cashbox_id = 524646d5-… (الرئيسية)
--   ✓ trial balance net = 0
--   ✓ cashboxes.current_balance == active CT signed sum on الرئيسية
--     (32,240 == 32,240 — three-way identity holds, see PR-265 deploy log)
--   ✓ financial_anomalies row exists for settlement7_reconciliation,
--     resolved=TRUE, resolved_at=2026-04-26T15:33:13Z (anomaly_id=2416)
--   ⚠ Abu Youssef 213 net credit = 2,371 (NOT 1,345 — see "Why we are
--     not just fixing the syntax" above; this drift is from legitimate
--     post-2026-04-26 activity, not a data integrity issue)
--
-- ─── How this PR fixes the runner ──────────────────────────────────────────
--
-- On the next container restart, the migration runner will:
--   1. See migration 110 not in schema_migrations (still pending)
--   2. Open a transaction and execute the body below
--   3. The DO block emits one NOTICE and returns successfully
--   4. INSERT INTO schema_migrations (filename='110_…', checksum=<sha1>) ✓
--   5. Migration 110 is now permanently recorded as applied — runner will
--      skip it on every subsequent restart, and the `✗ 110 — syntax error`
--      log line is gone forever.
--
-- ─── Out of scope ──────────────────────────────────────────────────────────
--
-- · No DML on the prod ledger / cashbox / business data
-- · No DDL / schema changes
-- · No engine/posting/financial-engine changes
-- · No changes to migrations.service.ts (the runner)
-- · No changes to any other migration file
-- ═══════════════════════════════════════════════════════════════════════════

DO $$
BEGIN
  RAISE NOTICE 'Migration 110 superseded — original PR-DRIFT-3G work already applied to production. See file header for state proof and git commit e7d340e for the original SQL.';
END $$;
