import {
  Column,
  CreateDateColumn,
  Entity,
  PrimaryGeneratedColumn,
} from 'typeorm';

/**
 * Mirrors the REAL `invoices` table schema from migration 006.
 * Column names intentionally match the SQL definitions — do NOT rename.
 */
@Entity({ name: 'invoices' })
export class InvoiceEntity {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  /** Auto-generated by BEFORE INSERT trigger (INV-YYYY-NNNNNN) */
  @Column({ type: 'varchar', length: 30, unique: true })
  invoice_no: string;

  @Column({ type: 'uuid' })
  warehouse_id: string;

  @Column({ type: 'uuid', nullable: true })
  customer_id: string | null;

  @Column({ type: 'uuid' })
  cashier_id: string;

  @Column({ type: 'uuid', nullable: true })
  salesperson_id: string | null;

  @Column({ type: 'uuid', nullable: true })
  shift_id: string | null;

  @Column({ type: 'varchar', length: 16, default: 'draft' })
  status: 'draft' | 'completed' | 'paid' | 'void' | 'refunded';

  @Column({ type: 'boolean', default: false })
  is_return: boolean;

  @Column({ type: 'boolean', default: false })
  is_exchange: boolean;

  @Column({ type: 'varchar', length: 20, default: 'pos' })
  source: string;

  @Column({ type: 'numeric', precision: 14, scale: 2, default: 0 })
  subtotal: number;

  @Column({ type: 'numeric', precision: 14, scale: 2, default: 0 })
  items_discount_total: number;

  @Column({ type: 'numeric', precision: 14, scale: 2, default: 0 })
  invoice_discount: number;

  @Column({ type: 'numeric', precision: 14, scale: 2, default: 0 })
  coupon_discount: number;

  @Column({ type: 'numeric', precision: 14, scale: 2, default: 0 })
  tax_amount: number;

  @Column({ type: 'numeric', precision: 5, scale: 2, default: 0 })
  tax_rate: number;

  @Column({ type: 'numeric', precision: 14, scale: 2, default: 0 })
  grand_total: number;

  @Column({ type: 'numeric', precision: 14, scale: 2, default: 0 })
  paid_amount: number;

  @Column({ type: 'numeric', precision: 14, scale: 2, default: 0 })
  change_amount: number;

  @Column({ type: 'text', nullable: true })
  notes: string | null;

  @CreateDateColumn({ type: 'timestamptz', name: 'created_at' })
  created_at: Date;

  @Column({ type: 'timestamptz', nullable: true })
  completed_at: Date | null;
}
